#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xE089DEF1D9C15D0D (release@tcpdump.org)
#
Name     : tcpdump
Version  : 4.9.2
Release  : 34
URL      : https://www.tcpdump.org/release/tcpdump-4.9.2.tar.gz
Source0  : https://www.tcpdump.org/release/tcpdump-4.9.2.tar.gz
Source1 : https://www.tcpdump.org/release/tcpdump-4.9.2.tar.gz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: tcpdump-bin = %{version}-%{release}
Requires: tcpdump-license = %{version}-%{release}
Requires: tcpdump-man = %{version}-%{release}
BuildRequires : libcap-ng-dev
BuildRequires : libpcap-dev
Patch1: CVE-2018-19519.patch
Patch2: CVE-2017-16808.patch
Patch3: CVE-2019-1010220.patch

%description
# tcpdump
[![Build
Status](https://travis-ci.org/the-tcpdump-group/tcpdump.png)](https://travis-ci.org/the-tcpdump-group/tcpdump)

%package bin
Summary: bin components for the tcpdump package.
Group: Binaries
Requires: tcpdump-license = %{version}-%{release}

%description bin
bin components for the tcpdump package.


%package license
Summary: license components for the tcpdump package.
Group: Default

%description license
license components for the tcpdump package.


%package man
Summary: man components for the tcpdump package.
Group: Default

%description man
man components for the tcpdump package.


%prep
%setup -q -n tcpdump-4.9.2
%patch1 -p1
%patch2 -p1
%patch3 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568218840
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$CFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$CFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1568218840
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/tcpdump
cp LICENSE %{buildroot}/usr/share/package-licenses/tcpdump/LICENSE
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/tcpdump
/usr/bin/tcpdump.4.9.2

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/tcpdump/LICENSE

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/tcpdump.1
