#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
#
# Source0 file verified with key 0xE089DEF1D9C15D0D (release@tcpdump.org)
#
Name     : tcpdump
Version  : 4.99.4
Release  : 43
URL      : https://www.tcpdump.org/release/tcpdump-4.99.4.tar.gz
Source0  : https://www.tcpdump.org/release/tcpdump-4.99.4.tar.gz
Source1  : https://www.tcpdump.org/release/tcpdump-4.99.4.tar.gz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: tcpdump-bin = %{version}-%{release}
Requires: tcpdump-license = %{version}-%{release}
Requires: tcpdump-man = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : libcap-ng-dev
BuildRequires : libpcap-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# TCPDUMP 4.x.y by [The Tcpdump Group](https://www.tcpdump.org/)
**To report a security issue please send an e-mail to security@tcpdump.org.**

%package bin
Summary: bin components for the tcpdump package.
Group: Binaries
Requires: tcpdump-license = %{version}-%{release}

%description bin
bin components for the tcpdump package.


%package license
Summary: license components for the tcpdump package.
Group: Default

%description license
license components for the tcpdump package.


%package man
Summary: man components for the tcpdump package.
Group: Default

%description man
man components for the tcpdump package.


%prep
%setup -q -n tcpdump-4.99.4
cd %{_builddir}/tcpdump-4.99.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1681399188
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1681399188
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/tcpdump
cp %{_builddir}/tcpdump-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/tcpdump/bf0cb439d0ca55615b5060ee09d77af3ddc9518d || :
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/tcpdump
/usr/bin/tcpdump.4.99.4

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/tcpdump/bf0cb439d0ca55615b5060ee09d77af3ddc9518d

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/tcpdump.1
