#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v19
# autospec commit: f35655a
#
# Source0 file verified with key 0xE089DEF1D9C15D0D (release@tcpdump.org)
#
Name     : tcpdump
Version  : 4.99.5
Release  : 44
URL      : https://www.tcpdump.org/release/tcpdump-4.99.5.tar.xz
Source0  : https://www.tcpdump.org/release/tcpdump-4.99.5.tar.xz
Source1  : https://www.tcpdump.org/release/tcpdump-4.99.5.tar.xz.sig
Source2  : E089DEF1D9C15D0D.pkey
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: tcpdump-bin = %{version}-%{release}
Requires: tcpdump-license = %{version}-%{release}
Requires: tcpdump-man = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : gnupg
BuildRequires : libcap-ng-dev
BuildRequires : libpcap-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# TCPDUMP 4.x.y by [The Tcpdump Group](https://www.tcpdump.org/)
**To report a security issue please send an e-mail to security@tcpdump.org.**

%package bin
Summary: bin components for the tcpdump package.
Group: Binaries
Requires: tcpdump-license = %{version}-%{release}

%description bin
bin components for the tcpdump package.


%package license
Summary: license components for the tcpdump package.
Group: Default

%description license
license components for the tcpdump package.


%package man
Summary: man components for the tcpdump package.
Group: Default

%description man
man components for the tcpdump package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) E089DEF1D9C15D0D' gpg.status
%setup -q -n tcpdump-4.99.5
cd %{_builddir}/tcpdump-4.99.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1726706840
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1726706840
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/tcpdump
cp %{_builddir}/tcpdump-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/tcpdump/bf0cb439d0ca55615b5060ee09d77af3ddc9518d || :
export GOAMD64=v2
GOAMD64=v2
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/tcpdump
/usr/bin/tcpdump.4.99.5

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/tcpdump/bf0cb439d0ca55615b5060ee09d77af3ddc9518d

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/tcpdump.1
